# Generated by Django 5.2.4 on 2025-07-24 10:13
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_typical_device_fingerprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeystrokeDynamics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(max_length=128, blank=True, null=True)),
                ("event_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.CASCADE, related_name="keystroke_dynamics", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
