# Generated by Django 5.2.4 on 2025-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_device_user_unique"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="core_docume_access__74d14c_idx",
        ),
        migrations.RemoveField(
            model_name="document",
            name="category",
        ),
        migrations.RemoveField(
            model_name="document",
            name="expiry_date",
        ),
        migrations.AlterField(
            model_name="document",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private (Owner Only)"),
                    ("DEPT", "Department Access"),
                ],
                default="PRIVATE",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["access_level"], name="core_docume_access__aad510_idx"
            ),
        ),
    ]
