# Generated by Django 5.2.4 on 2025-08-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_document_core_docume_access__74d14c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_high_risk_override',
            field=models.BooleanField(default=False),
        ),
    ]
