# Generated by Django 5.2.4 on 2025-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="required_access_level",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")], default=1
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="access_level",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")], default=1
            ),
        ),
    ]
