# Generated by Django 5.2.4 on 2025-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_document_required_access_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="azure_face_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
